---
- name: TEMPLATE - Add required permissions
  ansible.builtin.file:
    path: "{{ item }}"
    recurse: true
    state: directory
    owner: "root"
    group: "root"
    mode: "0777"
  loop:
    - "{{ docker_dir }}/template"

- name: TEMPLATE - Create template container
  community.docker.docker_container:
    name: template
    image: templateimagename:version
    restart_policy: always
    state: started
    pull: true
    privileged: true
    published_ports:
      - '900X:XXXX'
    # user: 'root:root'
    # network_mode: host
    networks:
      - name: homelab
    volumes:
      - "{{ docker_dir }}/template/data:/data"
    env:
      TEMPLATE: "template"
      # PUID: "{{ puid }}"
      # PGID: "{{ pgid }}"
      # TZ: "{{ timezone }}"
      # PASSWORD: "{{ default_pass }}"
