---
- name: NAS
  hosts: nas
  become: true
  vars_files: "../group_vars/nas/vars.yml"

  tasks:
    - name: nas - Deploy nas.domain.tld apps
      when: inventory_hostname == "nas.domain.tld"
      ansible.builtin.include_tasks: "../boilerplates/{{ item }}.yml"
      loop:
        - firefox                                                     # [9018]
        - excalidraw                                                  # [9017]
        - tautulli                                                    # [9016]
        - nfs                                                         # [2049]
        - filebrowser                                                 # [9015]
        - flood                                                       # [9014]
        - bazarr                                                      # [9013]
        - flaresolverr                                                # [9012]
        - scrutiny                                                    # [9010]
        - lidarr                                                      # [9009]
        - qbittorrent                                                 # [8888]
        - crafty                                                      # [9008]
        - samba                                                       # [445]
        - jellyfin                                                    # [8096]
        - prowlarr                                                    # [9006]
        - radarr                                                      # [9003]
        - sonarr                                                      # [9002]
        - overseerr                                                   # [9001]
        - unpackerr                                                   # [NULL]
        - cadvisor                                                    # [9098]
        - watchtower                                                  # NULL
        - portainer_agent                                             # [9099]
        - gitea_runner                                                # NULL
