---
- name: NAS
  hosts: nas
  become: true
  vars_files: "../group_vars/nas/vars.yml"

  tasks:
    - name: nas - Deploy nas.domain.tld apps
      when: inventory_hostname == "nas.domain.tld"
      ansible.builtin.include_tasks: "../boilerplates/{{ item }}.yml"
      loop:
        - bazarr                                                      # [9013]
        - flaresolverr                                                # [9012]
        - scrutiny                                                    # [9010]
        - lidarr                                                      # [9009]
        - qbittorrent                                                 # [8888]
        - crafty                                                      # [9008]
        - samba                                                       # [445]
        - jellyfin                                                    # [8096]
        - prowlarr                                                    # [9006]
        - whisparr                                                    # [9005]
        - jackett                                                     # [9004]
        - radarr                                                      # [9003]
        - sonarr                                                      # [9002]
        - overseerr                                                   # [9001]
        - plex                                                        # [5432]
        - deluge                                                      # [9000]
        - unpackerr                                                   # [NULL]
        - portainer_agent                                             # [9099]
        - cadvisor                                                    # [9098]
        - promtail                                                    # NULL
        - watchtower                                                  # NULL