---
- name: NET
  hosts: net
  become: true
  vars_files: "../group_vars/general/vars.yml"

  tasks:
    - name: NET - Deploy net.domain.tld apps
      when: inventory_hostname == "net.domain.tld"
      ansible.builtin.include_tasks: "../boilerplates/{{ item }}.yml"
      loop:
        - wireguard                                                   # 9004, 51820
        - adguard                                                     # 9003 [53, 67]
        - nginx                                                       # 9000 [80, 443]
        - cloudflare_ddns                                             # NULL
        - cloudflare                                                  # NULL
        - watchtower                                                  # NULL
        - cadvisor                                                    # [9098]
        - portainer_agent                                             # [9099]
