---
- name: NET
  hosts: net
  become: true
  vars_files: "../group_vars/general/vars.yml"

  tasks:
    - name: NET - Deploy net.domain.tld apps
      when: inventory_hostname == "net.domain.tld"
      ansible.builtin.include_tasks: "../boilerplates/{{ item }}.yml"
      loop:
        - tailscale                                                   # NULL
        - pialert                                                     # 9002
        - pihole                                                      # 9001 [53, 67]
        - nginx                                                       # 9000 [80, 443]
        - cloudflare                                                  # NULL
        - portainer_agent                                             # [9099]
        - watchtower                                                  # NULL
        - cadvisor                                                    # [9098]
        - promtail                                                    # NULL