---
- name: SERVICES
  hosts: services
  become: true
  vars_files: "../group_vars/general/vars.yml"

  tasks:
    - name: SERVICES - Deploy services.domain.tld apps
      when: inventory_hostname == "services.domain.tld"
      ansible.builtin.include_tasks: "../boilerplates/{{ item }}.yml"
      loop:
        - db_backup                                                   # NULL
        - duplicati                                                   # 9017
        - phpmyadmin                                                  # 9016
        - pgadmin                                                     # 9015
        - wordpress2                                                  # 9014
        - flood                                                       # 9013
        - wordpress                                                   # 9012
        - homepage                                                    # 9011
        - tautulli                                                    # 9010
        - drawio                                                      # 9003
        - flame                                                       # 9009
        - homeassistant                                               # 9008
        - joplin                                                      # 9007
        - filegator                                                   # 9006
        - ghost                                                       # 9005
        - ittools                                                     # 9002
        - stirling                                                    # 9001
        - pairdrop                                                    # 9000
        - portainer_agent                                             # [9099]
        - watchtower                                                  # NULL
        - cadvisor                                                    # [9098]
        - promtail                                                    # NULL